### ISSUE TITLE
IVertex parameter is null in OnBreadthFirstSearchCommand(IVertex vertex) method and Kruskal doesn't work

### ISSUE THREAD

**Issue by appcompat1** [mfe-/DataStructures.Algorithms#17]
**Repro steps:**
1. Clone the code from main branch and open with VS2022.
2. Press F5 to launch the DataStructures.UI.Demo project.
3. Select node 3 and right-click to choose BreadthFirstSearch option.
![image](https://user-images.githubusercontent.com/49433824/164204035-6a136959-8904-4284-ad11-d296746ffb88.png)

4. It will throw Object reference not set to an instance of an object at DataStructures.UI.Demo\Window1ViewModel.cs:line 116

**Findings:**
After checking the line 116, we found the vertex object is null.

**Another issue:**
1. Press F5 to launch the DataStructures.UI.Demo project.
2. Select node 3 and right-click to choose Kruskal option.

**Excepted Result:**
The screen should show this result.
![image](https://user-images.githubusercontent.com/49433824/164204667-cf537866-9ea6-491b-8358-7812887a8567.png)

**Actual Result:**
The screen doesn't do any changes. It keeps in this:
![image](https://user-images.githubusercontent.com/49433824/164204786-e3e50bba-f1ae-4a26-8ef7-9041834f21bb.png)

**Comment by mfe-** [comment]
Thanks @appcompat1 for reporting!
The null reference exception occurs, when no vertex is selected. I added an additional null check.

The current Kruskal implementation creates a new graph (by removing the existing edges and adding them again as long as no circle is detected. To display the new graph we need to "reset" the `GraphControl` by first setting it to `null` and afterwards setting the new kruskal graph. This is the reason why the vertices will be initialized at new random positions. For sure, this could be implemented in a nicer way, but as a fast fix it should be sufficient.
